## Numpy Concepts

In [1]:
import numpy as np

In [2]:
a = [[1,2,3],[4,5,6],[5,6,7]]

In [3]:
a

[[1, 2, 3], [4, 5, 6], [5, 6, 7]]

In [4]:
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [5]:
b.T

array([[1, 4, 5],
       [2, 5, 6],
       [3, 6, 7]])

In [6]:
c = np.array([[1,2,3],[3,4,5],[4,5,6]])

In [7]:
c

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [8]:
e = b.dot(c)
e

array([[19, 25, 31],
       [43, 58, 73],
       [51, 69, 87]])

In [9]:
b @ c

array([[19, 25, 31],
       [43, 58, 73],
       [51, 69, 87]])

In [12]:
f = np.where(e < 50, e, 10*e)
f

array([[ 19,  25,  31],
       [ 43, 580, 730],
       [510, 690, 870]])